### ISSUE TITLE
Template for Similarity 

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#1]
Create an new template for visual similarity, just like the one for instance similarity.

visual similarity template : https://vision.artresearch.net/resource/?action=edit&uri=Template%3Ahttp%3A%2F%2Fpurl.org%2Fontology%2Fsimilarity%2FSimilarity

instance similarity template : https://vision.artresearch.net/resource/:instancematching

**Comment by mafragias** [comment]
New Template has been created, but it's in the phase of testing, since there are currently no data in artresearch.

**Comment by AndreasMichelakis** [comment]
Please close this issue, a template exists and works well.
