### ISSUE TITLE
Create "same as" button for fields creator (artist) and repository

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#14]
This button would reconcile the artists and repositories in the vision instance.

**Comment by AndreasMichelakis** [comment]
Additional description:
Show the button only if one of the entities is from Wikidata or ULAN

**Comment by AndreasMichelakis** [comment]
Buttons have been created :

![image](https://user-images.githubusercontent.com/32819147/127135910-b80d877f-e99c-4d4f-a88b-6cf1ef0bdabd.png)
![image](https://user-images.githubusercontent.com/32819147/127136155-15225416-9dcb-477e-ab20-6604e216b7f4.png)
![image](https://user-images.githubusercontent.com/32819147/127136215-1bbeefe7-345f-4bdd-b944-e28f938935ee.png)


When clicked a modal appears with an interface similar to vocab.artresearch.net:

![image](https://user-images.githubusercontent.com/32819147/127136073-038c1bda-823c-4b7f-86f3-922d5667b00c.png)

**Comment by lklic** [comment]
Super!

Could you provide a link for testing?

**Comment by AndreasMichelakis** [comment]
An example of one containing both Creator & Repository matchings:
[link](https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fhertziana%2Fsource%2FHertziana&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F5021336799322110273712581)
