### ISSUE TITLE
"Imitation/Copy Of" assertion

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#16]
Change the name of Imitation to "Imitation/Copy Of" and have the option to choose which is the subject and the object of this relationship that would be created.

**Comment by AndreasMichelakis** [comment]
Additional description: 
Pressing the button should allow to select subject and object.
An assertion should be then created to the artresearch database.

**Comment by AndreasMichelakis** [comment]
All image assertion modals are now available. Clicking on one of the actions (i.e. Imitation/Copy of) a modal appears and users must select a pair of images. When that pair is selected the confirm button appears:

![image](https://user-images.githubusercontent.com/32819147/127166882-e38b7647-e0a6-495d-9f0e-3b72e8a2891d.png)

 Fields remain to be created & tested.

**Comment by AndreasMichelakis** [comment]
Fields & functionality have been implemented and work as expected. Please validate & close.
