### ISSUE TITLE
"Negative" Assertion

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#17]
The same negative assertion should reconcile also photographers

**Comment by AndreasMichelakis** [comment]
This has been completed UI-wise, respective fields remain to be created. 

![image](https://user-images.githubusercontent.com/32819147/127169597-5bd740e7-bfc0-4c47-83a7-b59328136f46.png)

Also see #16 .

**Comment by AndreasMichelakis** [comment]
Corresponding fields have been created and work as expected. Please validate & close.
