### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#18]
Create statistics page/ or indication in the similary page that would denote how many artworks are left to be reviewed.

**Comment by mafragias** [comment]
Also create a Dashboard for each repository

**Comment by AndreasMichelakis** [comment]
In each repository matchings page (see #19), a statistics element was added at the header, depicting how many artworks were matched and how many remain unmatched:
![image](https://user-images.githubusercontent.com/32819147/126772749-8311976b-a0e5-416b-a329-4b0347e73851.png)
e.g. for I Tatti :
![image](https://user-images.githubusercontent.com/32819147/126773276-d84d07a7-69bf-46c8-97e0-705f14582f85.png)

**Comment by AndreasMichelakis** [comment]
Please validate & close this.
