### ISSUE TITLE
Separate matching page for each Photo Archive

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#19]
Create a separate matching page for each Photo Archive, just like in the case of vocab, where all the reconciliations regarding one repository are in the same page.

**Comment by AndreasMichelakis** [comment]
Additional description: 
Keep existing implementation but provide single provider selection.

**Comment by AndreasMichelakis** [comment]
A separate option has been added to allow for selecting a single provider:
![image](https://user-images.githubusercontent.com/32819147/126762280-d9493042-96ba-4175-9098-a9cef796e86f.png)
After selecting one, a new page has been created that allows to view matchings from each other Photo archive as well as show a count for found matchings:
![image](https://user-images.githubusercontent.com/32819147/126762469-e25f7ff5-a7e5-4461-84d4-86ed5a2806e0.png)

**Comment by AndreasMichelakis** [comment]
Please validate & close this.
