### ISSUE TITLE
Similarity Page -> Go to next Similarity

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#20]
The next page should have the option to be a matching from a specific repository. For example if we have chosen to go on the page of specific repository (https://github.com/ArtResearch/vision-app/issues/19)  the next artwork that should be appearing should be from the same provider.

**Comment by AndreasMichelakis** [comment]
Additional description:
If for example matchings between I Tatti & KHI are selected, then the next similarity should also be between these two providers.

**Comment by AndreasMichelakis** [comment]
Done. Please validate & close.
