### ISSUE TITLE
Fix Query Timeout in Statistics

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#25]
Is it OK if we increase the memory for vision/vocab blazegraph, since now hold data for both instances?? We have noticed that it times out some count queries that have a lot of data within them, thus it will be useful, if we could increase it.

![image](https://user-images.githubusercontent.com/23557768/132514415-f0314ede-819c-43af-ada2-1d8b97b427db.png)

![image](https://user-images.githubusercontent.com/23557768/132879766-98564640-ae91-4747-a0fc-88e6f91edc63.png)

**Comment by lklic** [comment]
i have increased it from 30 to 50g.

Let me know if this helps

**Comment by mafragias** [comment]
It seems that this didn't fix the problem so I will repopen the issue with different title.

**Comment by AndreasMichelakis** [comment]
This is due to high number of entities being counted in order to produce the statistic. To improve this, we suggest having a chron task to update numbers used for the statistics , similarly to what @mafragias  did for the artresearch.net statistics page.   @lklic  @MinadakisNikos  Do you think we should proceed with this ?

**Comment by AndreasMichelakis** [comment]
After our discussion with @lklic , it was suggested that we proceed with the chron implementation. The interval should be the same with artresearch, update each day.

**Comment by mafragias** [comment]
Referencing the issue https://github.com/ArtResearch/vision-app/issues/26, which is collerated with this here. In order to place the statistics dashboard the statistics api needs to be implemented.

**Comment by mafragias** [comment]
implemented and tested, statistics-api now produces vision statistics, @AndreasMichelakis it's your turn to implement it in the frontend 💯

**Comment by AndreasMichelakis** [comment]
This was re-added to the frontend. Statistics are now received almost instantly, thus improving overall page load. Please validate & close.
