### ISSUE TITLE
Add statistics dashboard and menu item

### ISSUE THREAD

**Issue by lklic** [ArtResearch/vision-app#26]
Please create a statistics dashboard that contains all of the stats we are collecting from the various providers.

Also please add a menu item to the top right of header to access this page.

**Comment by AndreasMichelakis** [comment]
This has been implemented: 

![image](https://user-images.githubusercontent.com/32819147/138071170-e5a7f870-4dcd-4e4c-9802-f5c928723aa3.png)

Please validate & close.
