### ISSUE TITLE
Preferred title selection

### ISSUE THREAD

**Issue by AndreasMichelakis** [ArtResearch/vision-app#28]
### 1. Click on title and create same relation
![image](https://user-images.githubusercontent.com/32819147/139417036-78b34494-f238-48b2-a510-897cbfce98d9.png)

### 2. Click on "Same" button, popup appears and user selects the preferred title

**Comment by AndreasMichelakis** [comment]
@mafragias The options were added in the GUI. Appropriate fields remain to be created and added.

**Comment by mafragias** [comment]
I can confirm that the selection of Title works for the second option. But it doesn't work for the first option.

**Comment by mafragias** [comment]
I can confirm that now the buttons for the first option work, and I suggest this new button outlook : 
![image](https://user-images.githubusercontent.com/23557768/142222663-1f87a9d8-6597-44e5-85a1-d0ebfa9c7b8f.png)

**Comment by sophisid** [comment]
Matching Artist Button implementation
![image](https://user-images.githubusercontent.com/55842445/146749894-c53d616c-7495-48b2-9ef1-7ae4b04931b0.png)
