### ISSUE TITLE
Matching Statistics

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#3]
Statistics regarding the matches

**Comment by AndreasMichelakis** [comment]
This is an old issue, please provide an updated description of what statistics should appear in the statistics page.

**Comment by mafragias** [comment]
This has been implemented, however it still remains to figure out the https://github.com/ArtResearch/vision-app/issues/25
![image](https://user-images.githubusercontent.com/23557768/133056812-170d0e6d-1217-4163-8911-899b6d413b8a.png)

**Comment by AndreasMichelakis** [comment]
#25  Was fixed. Please validate & close this.
