### ISSUE TITLE
Upload image and search for artwork

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#4]
1)Upload an image
2)Save it locally
3)Search on pastec
4)Return artworks with similar images

A problem that I run into is, that the image that is saved cannot be accessed by pastec, because it doesn't have permission to read the image.

**Comment by AndreasMichelakis** [comment]
This has now been implemented by @sophisid and is available online:
![image](https://user-images.githubusercontent.com/32819147/140298725-afcfcc32-cdd9-4512-98b4-c1b8e70dbed1.png)
![image](https://user-images.githubusercontent.com/32819147/140298930-91fce36b-cd49-4c38-bdab-da307833c129.png)
![image](https://user-images.githubusercontent.com/32819147/140298962-ff8eb22d-aaad-4d01-9bf7-3d1688279925.png)

![image](https://user-images.githubusercontent.com/32819147/140298838-26f1b3b6-4e04-4035-8614-1a291cb94b6f.png)
![image](https://user-images.githubusercontent.com/32819147/140298860-b821e47a-2ca3-4708-a4c5-0a02ba05714f.png)
