### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#40]
Sometimes the page does not load correctly (functions on the right are missing)

![Screenshot 2021-12-13 141735](https://user-images.githubusercontent.com/73180833/145811118-9301a27a-1e61-4b17-869a-9bab38ffe504.png)

**Comment by mafragias** [comment]
Hi Spyros, if you find these kind of issues, please send the link also for us to better investigate the issue

**Comment by mafragias** [comment]
May I ask @spykoulouris , how did you end u to this similarity? Because the only way to get there without having the url parameters is using SPARQL endpoint, and in result not have the sidebar pop up.

**Comment by spykoulouris** [comment]
Didn't use sparql. I ended up to this matching once I selected Hertziana-Tatti through this page: https://vision.artresearch.net/resource/?uri=Default%3Amatchings 

I came across several times through this error.

**Comment by spykoulouris** [comment]
Happened again: 

https://vision.artresearch.net/resource/?uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F78233394111548515355105

That is a matching the system suggested to me after I clicked the "not similar" button for the previous matching

**Comment by mafragias** [comment]
@AndreasMichelakis Can you check this out, now that we have more info?

**Comment by mafragias** [comment]
I have resolved this issue, it only happened when you were selecting "Not similar", and it didn't keep the provider variables.
