### ISSUE TITLE
Creators: inverted names

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#41]
Should the creators names that are in inverted order ("name surname", or "surname, name") be proposed for matching as well?

(i.e. "Marconi, Rocco" and "Rocco Marconi"

![Screenshot 2021-12-13 143558](https://user-images.githubusercontent.com/73180833/145814056-d17c4039-f49f-4e90-9338-4ee53158fbe3.png)

**Comment by mafragias** [comment]
Proposals for matching artists only appear if any of the two creators have ULAN URI. For matching artists in a more refined way there is vocab.artresearch.net
