### ISSUE TITLE
Second reviewer

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#42]
The idea is that each matching should be reviewed twice by a different user?

The system suggests me to review matching that I have done: 
https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fhertziana%2Fsource%2FHertziana&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F11521334444331234546021

**Comment by spykoulouris** [comment]
Realized that the system does not allow the same user to review a matching made by him/herself. I get an error when I try to do so (see message on the top right corner). It would be useful to have a skip button so the user can move ahead to the next matching

![rev](https://user-images.githubusercontent.com/73180833/148512328-578b4de1-8771-404e-ad16-13a4c891077a.png)

**Comment by sophisid** [comment]
You can only see your reveiws from the dashboard. So when you are making reviews you won't have issue navigating. 
I just hidden the Select button for the already reviewed artworks.

**Comment by spykoulouris** [comment]
How does it work with proposed matchings that have been reviewed for the first time by another user?

In this case the matching has been done by Lukas, but there is not button to skip it.

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F7710267247457438553789361

<img width="1559" alt="Screenshot 2022-01-14 at 16 33 38" src="https://user-images.githubusercontent.com/73180833/149532915-25d38853-a4c4-42f4-9078-6fa185d85452.png">

**Comment by sophisid** [comment]
If two artworks are already been reviewed the user will not be able to see them through the "Artwork reconciliation "  as he makes similarities.
So when the user navigates from the reconciliation and expects to have a similarity he will never see an already reviewed pair of artworks. 
The already reviewed will ONLY be at the dashboard. 
If the user must navigate at the already reviewed artworks we must add a "Next reviewed" button.

**Comment by spykoulouris** [comment]
Not sure if I fully understand. 
You say that already reviewed matches are visible only through the dashboard, but I took the screenshot from the "Artwork reconciliation".

**Comment by mafragias** [comment]
@spykoulouris could you check skype ?
