### ISSUE TITLE
Duplicated titles

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#43]
Title showing up twice: 

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F409791778006001641037019515905

**Comment by mafragias** [comment]
As you can see now, this issue was resolved, by removing deprecated artwork title data : 

![image](https://user-images.githubusercontent.com/23557768/146180720-d7514b68-21f1-4775-87be-5a45d3a64f84.png)
