### ISSUE TITLE
Different images when opening a match

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#44]
Sometimes using the "details" button opens a matching with different images (of the same artwork).

For the first matching shown here:
![Screenshot 2021-12-15 104946](https://user-images.githubusercontent.com/73180833/146154054-17502a2f-f74c-45b2-90e1-87e350c13d0f.png)

I get this pair of images (the I Tatti image is a detail of the one one shown in the previous screen):
https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Fsource%2FFrick&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F790069850233250105040593565

**Comment by mafragias** [comment]
This is happening because we present in the list all the images related to the artwork, but in the matching page we present only the pair of images that have been found as a match. If we have more images matched between the two artworks it is presented like so:

![image](https://user-images.githubusercontent.com/23557768/146182562-0c2d22ac-c032-4022-b809-e14cb989eedb.png)

**Comment by sophisid** [comment]
@spykoulouris one visual solution is to call the component SimilarityListThumbnails in this page. 
![image](https://user-images.githubusercontent.com/55842445/146771460-f2a59f51-23bf-4048-aa57-7f874782fc0e.png)

**Comment by mafragias** [comment]
@spykoulouris what do you think about @sophisid 's suggestion?

**Comment by spykoulouris** [comment]
It looks beautiful. We can try this as well

**Comment by sophisid** [comment]
This has been implemented:
<img width="1428" alt="Screenshot 2022-02-02 at 11 00 37 AM" src="https://user-images.githubusercontent.com/55842445/152123795-340b276d-b291-4d30-87e8-876119b8eb33.png">
