### ISSUE TITLE
Artworks matchings button

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#45]
Since our main activity for now will be matching records across institutions, I propose to make this button more visible. 
Now it looks as being the same "vision" home page button.
![Screenshot 2021-12-15 104946](https://user-images.githubusercontent.com/73180833/146154733-2b97d018-247f-43ca-bd5c-5edc5736cdcc.png)

**Comment by AndreasMichelakis** [comment]
Thank you for this, the button element was changed be more visible and was also moved near the other navigation options.

![image](https://user-images.githubusercontent.com/32819147/146196303-03aadde4-aa11-4737-974e-f9d89da8ea7b.png)

Let us know if that is sufficient.

**Comment by spykoulouris** [comment]
great, thanks!
