### ISSUE TITLE
IIIF viewer for Frick

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#46]
IIIF viewer does not open when clicking on the Frick's images

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Fsource%2FFrick&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F256262517980214771479234805

![Screenshot 2021-12-15 105830](https://user-images.githubusercontent.com/73180833/146155350-aeb95389-d218-488f-b950-8fc2174f6870.png)

**Comment by spykoulouris** [comment]
Same problem with KHI's images:

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F9963511735472354970851092486

**Comment by AndreasMichelakis** [comment]
Hello @spykoulouris thank you for this.

@mafragias The following relation is missing from our data in vision:
```SPARQL
?image crm:P129i_is_subject_of ?imageManifest.
```
where ```?imageManifest``` is the image API manifest. 
This data exists in artresearch for all providers but not in vision.

**Comment by mafragias** [comment]
I add this relationship for testing in the example above, and it seems that it doesn't fix the issue. I wonder, why does it need the image api manifest? since for the case of itatti it doesn't?

**Comment by AndreasMichelakis** [comment]
This has been fixed and iiif images will be shown if existant:
[KHI example provided above](https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F9963511735472354970851092486)
![image](https://user-images.githubusercontent.com/32819147/146360651-5e174ff5-eddd-4ee9-bd32-adda879e460c.png)
[Frick example provided above](https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F9963511735472354970851092486)
![image](https://user-images.githubusercontent.com/32819147/146360987-7a7e6b9c-4c03-43ca-bc09-be59e9ee6569.png)

If a iiif image does not exist, a simple image is shown along with a message:
[Link](https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fhertziana%2Fsource%2FHertziana&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F1108417177613434010614461)
![image](https://user-images.githubusercontent.com/32819147/146361156-3c5aef19-02e4-4f42-9f18-6f2326fbb9d9.png)
"Currently there are no IIIF images for this Photo Archive"

@spykoulouris Please let us know if this is ok.

**Comment by mafragias** [comment]
It works now  for :
- [Frick](https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Fsource%2FFrick&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F256262517980214771479234805) 
![image](https://user-images.githubusercontent.com/23557768/160829297-a5b4e27c-8f6c-4b72-b4ca-f8071feb565a.png)
- [KHI] (https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F9963511735472354970851092486)
![image](https://user-images.githubusercontent.com/23557768/160829518-c7655fa1-c5c6-437e-b306-63529774bb7e.png)
