### ISSUE TITLE
Browsing matches

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#47]
Add the numbers of pages also on the top of the page. 

Also, when changing from one page to the other it is good see the top of the new screen

![InkedScreenshot 2021-12-15 110255_LI](https://user-images.githubusercontent.com/73180833/146156189-07947d2f-3877-4189-998e-9f40284579c7.jpg)

**Comment by AndreasMichelakis** [comment]
Thank you, now, when the pagination is clicked the user will be transfered to the top of the new page. 

Regarding adding the pagination to the top, this is not provided by the ResearchSpace semantic-table component and needs to be implemented in custom
