### ISSUE TITLE
Creators reconciliation stats

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#48]
Can we add in the statistics page a list (and the number) of the creators that have been reconciled?

Perhaps add a new tab for this?

**Comment by mafragias** [comment]
These information are kept in the vocab instance : https://vocab.artresearch.net/resource/?uri=Default%3AArtistStats

*Note : Vocab instance is under developement*

**Comment by sophisid** [comment]
![image](https://user-images.githubusercontent.com/55842445/149157254-31b1bd7e-d8b5-4284-b4e9-5f0d6dfcd743.png)
![image](https://user-images.githubusercontent.com/55842445/149157291-8b45eb8f-a5dd-4ff9-b71b-2f57950d5b4f.png)
