### ISSUE TITLE
Same button

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#50]
Same button is not working for both artworks and artists matchings

<img width="1751" alt="Screenshot 2021-12-28 at 19 41 55" src="https://user-images.githubusercontent.com/73180833/147593133-212a6796-564a-4384-995a-7af986f514de.png">

**Comment by mafragias** [comment]
This is not a bug. The idea behind the reconciliation of artists is that they would always match them with the one from ULAN. If one has not been identified as a ULAN artist (meaning that they have a ULAN URI) the same button for artists will not pop up.

**Comment by mafragias** [comment]
@spykoulouris Could you please explain on how it doesn't work on artworks ? Because I checked the buttons and verified that they work. 

Furthermore, in the case of artists only one should have the same button due to the fact that only one is coming from ULAN.

**Comment by spykoulouris** [comment]
When I click the same button to match artists (or the same/select buttons to match artworks) I get an error message "**failed to submit the form**".

You can see the error message on the right top corner of the screenshot provided here

**Comment by spykoulouris** [comment]
I close the issue. I was logged out and that's why I was getting the error message
