### ISSUE TITLE
Align artist matching button

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#51]
move the matching button for the artists in the same line with the artists names
https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Fsource%2FFrick&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F14171616846981188688087
![Screenshot 2022-01-03 123712](https://user-images.githubusercontent.com/73180833/147921425-e8d3ecd0-b809-4d92-942c-cfb609b0d494.png)

**Comment by sophisid** [comment]
![image](https://user-images.githubusercontent.com/55842445/148189463-09e1de49-73b4-4c46-944c-aff2f11a83e7.png)
Now the button is in the same row as the creator.
