### ISSUE TITLE
Wrong thumbnail images

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#53]
In the list of matches (|Marburg-I Tatti) there seems to be a wrong thumbnail image in the list.

![Screenshot 2022-01-03 132601](https://user-images.githubusercontent.com/73180833/147925370-26b10586-7678-403f-9e29-14e3aafdb8ba.png)

When I open the matching the images are correct:

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fmarburg%2Fsource%2FMarburg&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F74537697675912203445717924126

![Screenshot 2022-01-03 132334](https://user-images.githubusercontent.com/73180833/147925440-5a875a30-96fe-4713-8116-33ab2c752b89.png)

**Comment by mafragias** [comment]
Duplicate issue https://github.com/ArtResearch/vision-app/issues/44 ?

Would it be better if we just have in the list as thumbnails the images, that were matched? and in addition in the similarity page the list of photos of the artworks like it was proposed by @sophisid in #44

**Comment by spykoulouris** [comment]
@lklic what do you think?
