### ISSUE TITLE
Multiple values for artist

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#54]
When multiple values for creators exist, they should be split so we can match the correct ones.

i.e.: https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F859800553661998723179463288 

 in this artwork record the I Tatti record has two creators. the user should be able to match only the correct name with the creator provided by the Zeri
![Screenshot 2022-01-03 150332](https://user-images.githubusercontent.com/73180833/147933709-a81e6385-eab5-4bec-8cc8-ed45da628278.png)

**Comment by mafragias** [comment]
@sophisid distinct option for matching each artist (If it has ulan URI)
