### ISSUE TITLE
label: ulan prefered name

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#57]
Is it possible to see in this window the prefered name given by ULAN?

In this example "Bellini, Giovanni" instaed of "Gio Bellini"

![image](https://user-images.githubusercontent.com/73180833/148059311-a6469f92-4520-48a7-a219-2fff19e5ebc2.png)

http://vocab.getty.edu/page/ulan/500019244

**Comment by spykoulouris** [comment]
![500018362](https://user-images.githubusercontent.com/73180833/148059846-6bbca94e-5866-40e0-9fbe-71e830ce4894.png)

**Comment by mafragias** [comment]
we updated the ulan enrichment data labels for all the artists that didn't have label, which now have. 
example : 
Click for [Artist in Vision](https://vision.artresearch.net/resource/?uri=http://vocab.getty.edu/ulan/500018362)
![image](https://user-images.githubusercontent.com/23557768/160828246-c8e11f17-eb64-4e22-8a03-213e983b955a.png)
