### ISSUE TITLE
Photo ID field

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#58]
Could you please check the Zeri data provided in the Photo I.D. No. field?

In the example below it reads "Attributed to Antoniazzo Romano. The Birth of the Virgin, Antoniazzo Romano. "The Nativity of the Virigin", Antoniazzo Romano. Birth of the Virgin".

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F35545767782677875982682646

**Comment by mafragias** [comment]
For your example, now we present the Numeric IDs of the Zeri photos, instead of their title : 
![image](https://user-images.githubusercontent.com/23557768/158352608-d1a3e320-8327-44d8-8e2a-5f976d4007e5.png)
