### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#60]
Not sure what each one of the three tabs is in the dashboard. For example what is the difference between "test" and "reviewed" (it gives the same number of results). Does reviews include also matches marked as "not similar"?
https://vision.artresearch.net/resource/?uri=Default%3ADashboard 

Also it would be great to be able to short the matches by date/user/institutions/type of linke created (same negative, similar, etc.)

![dashboard](https://user-images.githubusercontent.com/73180833/148535677-47434ad7-2510-4560-9372-7bb39f397ac3.png)

**Comment by spykoulouris** [comment]
Is it possible to add here also a list of the artists matchings?

**Comment by sophisid** [comment]
The Test is an implementation of the reviewed but we are trying to add the filters functionality.

**Comment by mafragias** [comment]
@sophisid remove the test tab from the master branch and add it to a separete branch for testing. 

And If possible add the list of artists matchings suggested by spyros

**Comment by sophisid** [comment]
Test tab has been removed
