### ISSUE TITLE
IIIF I Tatti

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#61]
the IIIF viewer does not work for I Tatti images when doing matchings between I Tatti and the Zeri

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F912612203461218310309462778

**Comment by sophisid** [comment]
The two image url have different prefixes. 

IIIF :https://iiif.itatti.harvard.edu/iiif/2/fotoindex!001_recto-verso!001_recto-verso_d!001_recto-verso_box03_d!001_recto-verso_box03_d_00053.jpg/full/!500,500/0/default.jpg 
Not IIF: https://ids.lib.harvard.edu/ids/iiif/46197374/full/!500,500/0/native.jpg

IIIF: https://**iiif**.itatti.harvard.edu
Not IIIF :  https://**ids**.lib.harvard.edu

in artresearch we use the iiif mirador :
`<rs-iiif-mirador
        id="versoMirador"
        image-or-region="{{bindings.1.imageManifest.value}}"
        image-api-manifest-pattern="BIND(<{{bindings.1.imageManifest.value}}> as ?manifestUrl)"
      >
      </rs-iiif-mirador>`
So we need to find the right image-or-region and image-api-manifest-pattern

**Comment by spykoulouris** [comment]
Thanks it is fine now.

**Comment by spykoulouris** [comment]
I reopen this. Not sure why this is happening again.

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F265287051543824514964038440

**Comment by sophisid** [comment]
The IIIF for the photos is now working online.
