### ISSUE TITLE
Imitation/copy of relationship

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#62]
Could you add the name of the repository (i.e., I Tatti, Zeri, etc.) above the images in the imatation / copy of page?
That way it will be easier to describe which artwork is the copy and which is the original work.

![imitation](https://user-images.githubusercontent.com/73180833/148765718-ff82b1dd-1cd0-45c0-acd0-4a9741f6f87c.png)

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fmarburg%2Fsource%2FMarburg&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F24529365353993644064734801455

**Comment by sophisid** [comment]
Added Photo archive label and image 
![image](https://user-images.githubusercontent.com/55842445/149321054-f0ab3e20-5fdf-495a-bd92-38b9b1f64a72.png)

**Comment by spykoulouris** [comment]
Thanks!
