### ISSUE TITLE
Dashboard - Marked for review

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#66]
What is the **delete** button for min the Marked for review list of matchings in the dashboard?

Also when I try to edit a matching in that list ("view details" button) I get an error message.

<img width="1470" alt="Screenshot 2022-01-19 at 11 27 31" src="https://user-images.githubusercontent.com/73180833/150104475-223ad2ed-b617-4375-8c65-d0b1c1885adb.png">

**Comment by sophisid** [comment]
@spykoulouris please send the iri of this example

**Comment by spykoulouris** [comment]
Here is an example:

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F250357436218551994055695504677

**Comment by sophisid** [comment]
Delete button is for in case of a mistake in the review. So if you press the delete button the **isReviewed** will be **false** and it will appear again to the Reconsiliation. 
If you go to this similarity https://vision.artresearch.net/resource/Similarity/250357436218551994055695504677 .
and review it . Then go to Your dashboard and then press view details you have to land to this page :
![image](https://user-images.githubusercontent.com/55842445/150164442-6a86dc2a-37f8-4c25-ac07-75a2c11e2b23.png)
in any other case please let me now
