### ISSUE TITLE
clean up matched image sidebar

### ISSUE THREAD

**Issue by lklic** [ArtResearch/vision-app#71]
Please add the score  to the right of the images and some padding between the them

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F31435182964652524477482912

![image](https://user-images.githubusercontent.com/6654854/153608559-eed648ae-797e-447f-9be6-a592ef53dd0e.png)

**Comment by sophisid** [comment]
Pastec score for every pair of image and padding added in between.
![image](https://user-images.githubusercontent.com/55842445/153826998-21fd215e-53bc-4bde-a9c5-d83a64ee04e8.png)
