### ISSUE TITLE
match artist button returns error

### ISSUE THREAD

**Issue by lklic** [ArtResearch/vision-app#73]
https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F13401672294796686294441747

![image](https://user-images.githubusercontent.com/6654854/153609394-abfad64e-f115-4467-bea3-ff72f00e32e9.png)

**Comment by sophisid** [comment]
the field definition was wrong, now fixed

**Comment by spykoulouris** [comment]
Now matching an artist the page reloads, but the yellow "match artists" button does not disappear

**Comment by spykoulouris** [comment]
https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F4811397370410800831904391735

**Comment by spykoulouris** [comment]
Artist reconciliation bug example @mafragias : 

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F1056279129672712541313

**Comment by mafragias** [comment]
Hi @spykoulouris , I made an update and I want you to test out your example to see if the issue with the failed to submit persists.

**Comment by mafragias** [comment]
@spykoulouris, have you encountered this issue again?

**Comment by spykoulouris** [comment]
No, thank you
