### ISSUE TITLE
Platform Dashboard for all matches

### ISSUE THREAD

**Issue by lklic** [ArtResearch/vision-app#76]
We need a general platform dashboard named "Platform Dashboard" that shows all matches by all users with role "collection-curator".

This should be accessible from the top right of "my dashboard" as a link.

![image](https://user-images.githubusercontent.com/6654854/153614264-4137989d-411d-430a-b9f6-2b1383f48e82.png)

Users with this role should also be able to add a note for a given matching and move it to a "For review" queue. At that point the records should be "unmerged".

The matching will then show up in the original users' queue with the comment, that will allow them to review the matching again.

**Comment by sophisid** [comment]
The platform dashboard :
![image](https://user-images.githubusercontent.com/55842445/153879959-c21c10d4-bc87-45e9-81eb-a704c4310f97.png)
a tab "for review " is added for the ones with additional info

**Comment by sophisid** [comment]
the button for the curator-collection to go to the platfrom dashboard
![image](https://user-images.githubusercontent.com/55842445/153880272-14c6e4f0-51cb-4db7-899d-f857cf98a413.png)
