### ISSUE TITLE
Part of error

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#77]
<img width="1381" alt="Screenshot 2022-02-19 at 10 21 30" src="https://user-images.githubusercontent.com/73180833/154793082-04cff4a5-1a75-4bf3-9dc5-1b74c7d608f5.png">

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F53356284741513632946025165

**Comment by sophisid** [comment]
Is part of and version of, are now working.
![image](https://user-images.githubusercontent.com/55842445/154918300-865eb3fa-f6fc-42bc-ba0b-2744c0afb46e.png)
![image](https://user-images.githubusercontent.com/55842445/154918864-205196c1-c9e4-46bc-b87b-b2a981ea0f51.png)
