### ISSUE TITLE
same matches

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#78]
The system keeps suggesting me the same matches again and again. Can you check what has happened to these **imitation/copy of** and **part of** matchings? There should be a problem to matchings put in these lists.

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F557485325426684275983823161

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F99731854768189369835824044547

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F880805588624285278646586077

**Comment by spykoulouris** [comment]
same here
https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F3469765879466230997635278

**Comment by sophisid** [comment]
The problem was that some of the relations of similarities did not assert a "reviewed" value.
This now works properly.

**Comment by spykoulouris** [comment]
Can you check again? This is a "part of" matching I already did, but the "reviewed" value is not there and the system suggests the matching again.
https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F3469765879466230997635278

**Comment by mafragias** [comment]
Reviewed value is now there : 
![image](https://user-images.githubusercontent.com/23557768/158342663-c3d1e7a8-c50b-4a9b-9e0c-25a6d659536b.png)
