### ISSUE TITLE
Bug on list of results of matches

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#79]
Louisa Quote: "On a number of searches (Frick/I Tatti) I was getting this result for the title:" 
![unnamed](https://user-images.githubusercontent.com/23557768/155280383-a569ac7c-9994-473e-b220-dd66f72b215a.png)

**Comment by sophisid** [comment]
The titles have special characters ' [ , ] , ' , " , \ , / , ( , )'and they cannot appear properly through the queries.

**Comment by mafragias** [comment]
fixed
