### ISSUE TITLE
Frick additional photos bug

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#80]
From Louisa:
- [x] A number of the Frick’s “additional photos” were not loading in mirador pop-out screen.
- [x] It would be helpful if when the mirador popped up the additional photos, you could scroll through the remaining additional photos from the pop-up instead of having to close the pop up and pick the next photo.  Is this possible?

**Comment by sophisid** [comment]
The mirador is now fixed.
The scrolling through the photos is a very heavy query and it takes too much time to load. Will add it again and let the commitee deside.

**Comment by sophisid** [comment]
The mirador (IIIF Viewer) is now working in all cases.
