### ISSUE TITLE
"Failed to submit form"

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#81]
Louisa Quote "Starting to get “failed to submit form” when matching artists after about 25 mins in site. "

**Comment by sophisid** [comment]
Either the user is not logged in, or their session time has been terminated and they need to log out and log in again. 
Probably we can change the session time through the platfrom

**Comment by sophisid** [comment]
![image](https://user-images.githubusercontent.com/55842445/155303451-92e3a78f-98ae-468e-a705-ba1e9adc5ab3.png)
30 minutes

**Comment by sophisid** [comment]
changed variables
