### ISSUE TITLE
Name in Match artists

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#82]
Louisa Quote: "When matching artists, Frick/I Tatti, sometimes it shows the Frick name as the Itatti name (pic1) or just the Getty name (pic 2) "
![unnamed](https://user-images.githubusercontent.com/23557768/155281783-ebb6f2d0-01b4-4afa-8821-d7011b54d478.png)
![unnamed](https://user-images.githubusercontent.com/23557768/155281787-c83e30e5-0959-4212-85ef-40df99f495e7.png)

**Comment by sophisid** [comment]
We have not seen other examples that the table has revert Artists values.
But the fact that it shows only one title in the pop up is not wrong. The "match artist" button appears if the one of the two artists has been matched from the vocab so the user can be able to match the second with the Getty (ULAN) value of the artist.
