### ISSUE TITLE
Artists Dashboard

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#90]
Add Tab to dashboard for matched artists

**Comment by sophisid** [comment]
A dashboard with the matched artists is now available. Also there are links to the artresearch and getty/wikidata of each. 
Added also a button to the vocab website to the up-right.
<img width="1427" alt="Screenshot 2022-03-09 at 5 33 10 PM" src="https://user-images.githubusercontent.com/55842445/157474580-0bfa6e66-1cdf-4105-b2d5-c75c0230a5c8.png">
<img width="125" alt="Screenshot 2022-03-09 at 5 28 37 PM" src="https://user-images.githubusercontent.com/55842445/157473937-7d63ab72-309a-4a4f-a0d4-5f977ad7c409.png">
