### ISSUE TITLE
"Is part of" artwork matching

### ISSUE THREAD

**Issue by lklic** [ArtResearch/vision-app#93]
I think it would be good to extend the "is part of" functionality of the matching to add a specific photo (that is part of a larger group of works) to the artwork record that represents a specific work within the larger group.

In the following matching example, the Zeri has cataloged a smaller part of a whole that is represented in the I Tatti record. With our current implementation of "is part of", a link will be added to both records to indicate that one is part of another.
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/6654854/156354523-27e0d2ff-c9a4-49c9-bdfc-a122fb2fc48b.png">

I think we should extend this functionality to connect the specific photo from the I tatti work and connect it to the artwork record of the Zeri as well.

@spykoulouris in your experience will this approach work in 100% of the cases?

**Comment by spykoulouris** [comment]
This kind of cataloging is very common at the Zeri. They have cataloged as predellas, or secondary scenes of frescoes as separate artworks. In these cases I've been using the "is part of" relationship to match them with the I Tatti records.

If I understand correctly you mean showing also the opposite relationship "has part" to the I Tatti recods. Is that what you mean @lklic ?

**Comment by lklic** [comment]
We are already showing the opposite relationship. What I mean is to take the specific photograph record and attach it to the artwork record of the Zeri. This way if someone pulls up that artwork record, it will have I Tatti photos as well, even though the artwork data will be not be merged as it refers to another artwork.

Can you confirm that this would work for all of the cases that you have matched so far?

**Comment by spykoulouris** [comment]
Ok. Now I see what you mean.

That might be an option. Perhaps extending this to all suggestions of pastec, the ones provided on the left?
