### ISSUE TITLE
Add location to the repositories matching

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#96]
In the matching repositories pop up, the location of the the respective repository should appear:

Example : https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F1056279129672712541313
- pop up :
![image](https://user-images.githubusercontent.com/23557768/158334859-b51dee8a-76dd-436e-a85f-d2add48b0d82.png)
- repository location : 
(the location can be either on repository location )
![image](https://user-images.githubusercontent.com/23557768/158334987-9d461b56-d1ef-4d9b-9a3d-83ca5428a34c.png)
(or in current location)
![image](https://user-images.githubusercontent.com/23557768/158335026-3c17519a-05ec-4514-9c33-59aa605f8bcc.png)

**Comment by sophisid** [comment]
![image](https://user-images.githubusercontent.com/55842445/158631567-cf1aa5fa-3404-40c1-ab2e-c6d1b79a936c.png)
The modal now appears also the location.
