### ISSUE TITLE
Skipped matchings

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#97]
In many cases the system gives an error when trying to review skipped matchings.

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F5153837331682605764494466569

**Comment by mafragias** [comment]
Hey @spykoulouris , I made an update to  your user permissions, can you check and verify, that now it works for you?

**Comment by spykoulouris** [comment]
Ok, I'll check it
